using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HabboEncryption.Keys
{
    public class DiffieHellmanKeyHolder
    {
        /* 
         * Keys original generated by Joopie
         * Date: 20-09-2014
         */

        public string P = "EF258992BFD03247B7B83A9163F9ED7681D2174BCAF8A213590AEB82CB75B3897A18A53EDA19D0911021ED80F9466F672080C20C4AF60414A76E6921C8A32A87";
        public string G = "C215323F4DA5E822318243344B023AFE69B8B310389C73EC91F6260B994FE7518A2886B9792F3FBC297CD5707AB7A14632C290DAE8B7F56780AB50D39AC38A2D";
    }
}
