using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HabboEncryption.Keys
{
    public class DiffieHellmanKeyHolder
    {
        /* 
         * Keys original generated by Joopie
         * Date: 20-09-2014
         */

        public string Prime = "";
        public string Generator = "";
    }
}
